################# TESTE 1

echo "ADDCAR TEAM: AA, CAR: 10, SPEED: 3300, CONSUMPTION: 3, RELIABILITY: 95" > named_pipe
echo "ADDCAR TEAM: BB, CAR: 20, SPEED: 3400, CONSUMPTION: 3, RELIABILITY: 95" > named_pipe
echo "ADDCAR TEAM: BB, CAR: 20, SPEED: 4000, CONSUMPTION: 5.5, RELIABILITY: 80" > named_pipe
echo "ADDCAR TEAM: BB, CAR: 21, SPEED: 4000, CONSUMPTION: 5.5, RELIABILITY: 80" > named_pipe
echo "ADDCAR TEAM: BB, CAR: 22, SPEED: 3800, CONSUMPTION: 3.8, RELIABILITY: 80" > named_pipe
echo "START RACE!" > named_pipe
echo "ADDCAR TEAMS: CC" > named_pipe


################# TESTE 2

echo "ADDCAR TEAM: AA, CAR: 10, SPEED: 3300, CONSUMPTION: 3, RELIABILITY: 100" > named_pipe
echo "ADDCAR TEAM: BB, CAR: 20, SPEED: 3400, CONSUMPTION: 3, RELIABILITY: 100" > named_pipe
echo "ADDCAR TEAM: BB, CAR: 21, SPEED: 4000, CONSUMPTION: 5.5, RELIABILITY: 100" > named_pipe
echo "ADDCAR TEAM: CC, CAR: 30, SPEED: 2600, CONSUMPTION: 1.5, RELIABILITY: 100" > named_pipe
echo "ADDCAR TEAM: DD, CAR: 40, SPEED: 3000, CONSUMPTION: 4, RELIABILITY: 100" > named_pipe
echo "ADDCAR TEAM: DD, CAR: 41, SPEED: 3000, CONSUMPTION: 4, RELIABILITY: 100" > named_pipe
echo "START RACE!" > named_pipe
echo "ADDCAR TEAM: CC, CAR: 31, SPEED: 2600, CONSUMPTION: 1.5, RELIABILITY: 100" > named_pipe


################# TESTE 3

echo "ADDCAR TEAM: AA, CAR: 10, SPEED: 3300, CONSUMPTION: 3, RELIABILITY: 75" > named_pipe
echo "ADDCAR TEAM: BB, CAR: 20, SPEED: 3400, CONSUMPTION: 3, RELIABILITY: 75" > named_pipe
echo "ADDCAR TEAM: BB, CAR: 21, SPEED: 4000, CONSUMPTION: 5.5, RELIABILITY: 60" > named_pipe
echo "ADDCAR TEAM: CC, CAR: 30, SPEED: 2600, CONSUMPTION: 1.5, RELIABILITY: 100" > named_pipe
echo "ADDCAR TEAM: DD, CAR: 40, SPEED: 3000, CONSUMPTION: 4, RELIABILITY: 90" > named_pipe
echo "ADDCAR TEAM: DD, CAR: 41, SPEED: 3000, CONSUMPTION: 4, RELIABILITY: 90" > named_pipe
echo "START RACE!" > named_pipe


################# TESTE 4

echo "ADDCAR TEAM: AA, CAR: 10, SPEED: 3300, CONSUMPTION: 3, RELIABILITY: 75" > named_pipe
echo "ADDCAR TEAM: BB, CAR: 20, SPEED: 3400, CONSUMPTION: 3, RELIABILITY: 75" > named_pipe
echo "ADDCAR TEAM: BB, CAR: 21, SPEED: 4000, CONSUMPTION: 5.5, RELIABILITY: 60" > named_pipe
echo "ADDCAR TEAM: CC, CAR: 30, SPEED: 2600, CONSUMPTION: 1.5, RELIABILITY: 100" > named_pipe
echo "ADDCAR TEAM: DD, CAR: 40, SPEED: 3000, CONSUMPTION: 4, RELIABILITY: 90" > named_pipe
echo "ADDCAR TEAM: DD, CAR: 41, SPEED: 3000, CONSUMPTION: 4, RELIABILITY: 90" > named_pipe
echo "START RACE!" > named_pipe
